### ISSUE TITLE
get_choice_input for chip selection?

### ISSUE THREAD

**Issue by ZetaTwo** [fluxchief/binaryninja_avr#1]
I just started using and exploring binja so this might be totally idiotic idea but I'm going to ask here anyway. Sorry if that is the case.

Isn't it possible to use the [get_choice_input](https://api.binary.ninja/binaryninja.interaction.get_choice_input.html) API to ask for the exact chip when the plugin is used instead of hardcoding it?

**Comment by fluxchief** [comment]
Hey, last time I tried this it caused BinaryNinja to crash. I guess the architecture plugin is initialized at some point where you are not supposed to ask for user input and you cannot change it afterwards since it already sets some things up during architecture initialization.

**Comment by ZetaTwo** [comment]
I went ahead and tried by adding a call to get_choice_input in `__init__.py:33` and it actually worked. It looks a little bit silly though since it asks before even showing the main GUI and I guess that means it will ask every time you start binja.

**Comment by fluxchief** [comment]
Cool. Though I'm not sure whether this is a good solution. I think it is better to change this one line python code instead of getting nagged all the time about this.
What do you think?

**Comment by ZetaTwo** [comment]
Probably, yeah. I mean, the ideal would be to have it when you load a file, like in IDA but I don't know how that would be done so for now it's probably best to leave it as is.

**Comment by fluxchief** [comment]
"Solved" by https://github.com/fluxchief/binaryninja_avr/commit/68f1907c5e15123d544535813a5614c2daabb5f4
