### ISSUE TITLE
Installing from the plugin manager does not seem to work.

### ISSUE THREAD

**Issue by ZetaTwo** [fluxchief/binaryninja_avr#12]
I went to the plugin manager, clicked the plugin, installed it, tried enabling it and got the following in the log:
```
Failed to import python plugin: community/fluxchief_binaryninja_avr: No module named 'binaryninja_avr'
Failed to enable plugin:
AVR Architecture Plugin
Check the log for more details
```

**Comment by fluxchief** [comment]
Looks like the plugin manager clones it into a folder `fluxchief_binaryninja_avr` while the project itself is called `binaryninja_avr` and therefore can't import it properly.

Not sure right now how to **properly** fix it, will try to figure sth out.

**Comment by ZetaTwo** [comment]
I think you should use relative imports, for example:

replace
```
from binaryninja_avr import operand
from binaryninja_avr.operand import RAM_SEGMENT_BEGIN
```

with
```
import .operand
from .operand import RAM_SEGMENT_BEGIN
```

**Comment by fluxchief** [comment]
Should be resolved now :) Thanks!
