### ISSUE TITLE
Replace chip select dropdown with load settings

### ISSUE THREAD

**Issue by ZetaTwo** [fluxchief/binaryninja_avr#13]
Displaying a UI element while creating the BinaryView breaks the loading.
Instead of using a modal to select the chip, load settings can be used.
An example can be found here: https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/mappedview.py 

The issue was also discussed in the Binary Ninja Slack: https://binaryninja.slack.com/archives/C0CVALTLN/p1615425098046000

**Comment by fluxchief** [comment]
I've implemented this in 1488bb4bdb8c1d5686a5ff5e2baa2042cb8e3160.

I don't think it's done fully correctly - I'm setting `AVR.chip` to the used class, ideally it should be `self.chip` but that resulted in binaryninja not responding and behaving weirdly - but at least it works (on my machine (TM)).

**Comment by psifertex** [comment]
Thanks! FYI, you don't have to create an issue upstream for us to update the plugin anymore, we're tracking releases and automatically added the update to the plugin manager.
