### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ghost** [fluxchief/binaryninja_avr#2]
I need more complete installation instructions.  I followed the existing instructions on OSX and Mint Linux without any success.  It seems that BN should recognize the binaryninja_avr plugin in the plugin directory accessible from the Tools menu.

**Comment by fluxchief** [comment]
This plugin won't appear in the tools menu. instead you can select 'Atmel AVR' in the bottom right to switch the architecture.
This should not be required as it will automatically switch to this if you open a valid bin file.

Note: ihex files are not supported at the moment.
