### ISSUE TITLE
LLIL for conditional branches is incorrect

### ISSUE THREAD

**Issue by KarlVogel** [fluxchief/binaryninja_avr#6]
https://github.com/fluxchief/binaryninja_avr/blob/84f0b3f890d9e66509bddb92d77ada5444a2d1be/instructions.py#L564

Looks like a copy and paste issue. Shouldn't the 'is set' variants be using il.const(1, 1) ?

**Comment by fluxchief** [comment]
Yep, sounds about right. I'll push a fix soon.

**Comment by fluxchief** [comment]
Should be fixed now.
